In [1]:
# Import the dependencies.
import pandas as pd
import requests
# Import the API key.
from config import g_key

In [2]:
#!pip install gmaps

In [3]:
#pip install gmaps

In [4]:
import gmaps

In [5]:
# Store the CSV you saved created in part one into a DataFrame.
city_data_df = pd.read_csv("weather_data/cities.csv")
city_data_df.head()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Bredasdorp,ZA,2021-12-08 20:10:22,-34.5322,20.0403,65.28,89,99,12.55
1,1,Butaritari,KI,2021-12-08 20:10:22,3.0707,172.7902,82.40,77,99,12.86
2,2,Nikolskoye,RU,2021-12-08 20:10:22,59.7035,30.7861,10.29,100,97,2.68
3,3,Bluff,NZ,2021-12-08 20:10:23,-46.6000,168.3333,52.81,87,100,4.14
4,4,Kinablangan,PH,2021-12-08 20:10:23,7.6947,126.5503,76.66,80,100,5.95

In [6]:
#Getting data types.
city_data_df.dtypes

City_ID         int64
City           object
Country        object
Date           object
Lat           float64
Lng           float64
Max Temp      float64
Humidity        int64
Cloudiness      int64
Wind Speed    float64
dtype: object

In [7]:
#Create a Maximum Temperature Heatmap

In [8]:
# Configure gmaps to use your Google API key.
gmaps.configure(api_key = g_key)

In [9]:
#Next, create the heatmap for the maximum temperature. The general syntax for creating a heatmap is as follows.

In [10]:
max_temp = city_data_df["Max Temp"]
temps = []
for temp in max_temp:
    temps.append(max(temp, 0))

temps

[65.28,
 82.4,
 10.29,
 52.81,
 76.66,
 80.17,
 74.95,
 31.01,
 6.91,
 72.28,
 66.04,
 48.92,
 75.69,
 21.13,
 72.16,
 84.15,
 72.28,
 90.55,
 0,
 58.68,
 52.83,
 54.86,
 30.51,
 0,
 50.25,
 57.47,
 6.53,
 6.87,
 78.85,
 0,
 33.62,
 65.55,
 33.66,
 48.58,
 85.51,
 78.04,
 36.07,
 34.02,
 13.21,
 67.86,
 69.35,
 81.54,
 13.5,
 8.6,
 58.1,
 29.52,
 70.77,
 57.83,
 0,
 78.08,
 71.73,
 6.42,
 64.13,
 76.12,
 74.68,
 80.76,
 77.79,
 57.31,
 54.91,
 54.18,
 28.13,
 80.22,
 81.68,
 3.83,
 13.89,
 18.93,
 91.35,
 73.96,
 77.45,
 68.86,
 54.95,
 10.71,
 21.79,
 82.38,
 28.04,
 45.12,
 79.86,
 61.79,
 79.9,
 46.02,
 15.87,
 1.33,
 36.09,
 82.49,
 33.76,
 52.48,
 69.19,
 80.49,
 7.29,
 51.37,
 56.82,
 71.58,
 82.42,
 0,
 81.79,
 60.91,
 0,
 0,
 69.64,
 78.15,
 50.63,
 70.63,
 47.12,
 30.88,
 50.67,
 65.75,
 70.52,
 71.83,
 89.82,
 71.37,
 24.64,
 36.91,
 49.23,
 79.48,
 41.07,
 60.03,
 11.95,
 11.1,
 76.71,
 16.36,
 7.59,
 81.68,
 10.26,
 61.2,
 81.1,
 86.05,
 78.58,
 67.32,
 8.69,
 2.39,
 55.15,
 55.72,
 82.13,
 81.12,
 75.54,
 77.11,
 44.46,
 67.87,
 78.91,
 26.51,
 65.8,
 46.33,
 70.21,
 6.13,
 30.29,
 60.85,
 75.63,
 74.79,
 77.99,
 0,
 82.17,
 62.02,
 78.01,
 8.62,
 39.54,
 80.04,
 78.22,
 0,
 73.08,
 21.27,
 78.26,
 36.01,
 31.68,
 75.47,
 61.2,
 0,
 14.0,
 82.26,
 71.78,
 56.79,
 0,
 80.56,
 36.57,
 79.88,
 63.88,
 76.08,
 6.24,
 22.15,
 69.73,
 66.09,
 75.18,
 27.82,
 72.57,
 60.39,
 64.06,
 3.69,
 78.76,
 82.08,
 69.67,
 21.38,
 61.79,
 56.01,
 78.48,
 68.59,
 41.74,
 59.41,
 81.57,
 78.75,
 81.52,
 30.7,
 9.21,
 52.48,
 82.63,
 80.83,
 16.07,
 60.66,
 83.88,
 37.42,
 63.68,
 71.69,
 67.15,
 83.98,
 84.18,
 81.01,
 65.16,
 41.65,
 86.63,
 73.87,
 69.84,
 53.87,
 78.49,
 4.89,
 63.86,
 90.09,
 69.46,
 82.51,
 69.51,
 73.92,
 91.33,
 7.65,
 30.02,
 58.1,
 30.42,
 63.21,
 60.57,
 59.95,
 65.48,
 10.44,
 0,
 64.02,
 86.22,
 82.06,
 42.8,
 10.72,
 41.9,
 80.71,
 55.74,
 88.0,
 72.19,
 28.27,
 77.36,
 57.67,
 72.55,
 34.27,
 83.08,
 38.97,
 73.24,
 69.71,
 71.51,
 72.18,
 77.38,
 70.12,
 77.59,
 55.54,
 76.77,
 0,
 0,
 93.9,
 79.2,
 0,
 81.07,
 39.42,
 85.59,
 42.64,
 79.5,
 4.98,
 0,
 60.28,
 38.44,
 73.42,
 75.04,
 28.2,
 64.96,
 70.63,
 74.39,
 6.39,
 98.08,
 40.12,
 77.47,
 25.48,
 50.72,
 84.16,
 74.66,
 77.18,
 74.98,
 73.58,
 64.15,
 85.44,
 15.75,
 73.98,
 22.96,
 0,
 31.77,
 28.15,
 60.53,
 74.26,
 46.8,
 78.93,
 65.8,
 62.1,
 80.47,
 30.81,
 79.12,
 0,
 58.86,
 71.76,
 16.52,
 58.86,
 64.13,
 65.07,
 39.11,
 0,
 21.25,
 61.36,
 61.5,
 76.08,
 84.2,
 64.58,
 77.95,
 39.09,
 43.45,
 56.35,
 82.89,
 0,
 76.68,
 73.04,
 78.73,
 38.66,
 42.1,
 81.12,
 73.36,
 49.06,
 56.79,
 78.93,
 71.67,
 0,
 80.38,
 81.81,
 62.01,
 70.29,
 32.09,
 80.78,
 32.07,
 60.87,
 64.78,
 68.68,
 79.72,
 0,
 90.95,
 56.03,
 44.89,
 57.22,
 62.58,
 65.26,
 2.98,
 52.81,
 25.88,
 10.74,
 79.77,
 8.58,
 87.57,
 77.31,
 10.35,
 32.54,
 44.98,
 77.09,
 71.55,
 42.39,
 7.03,
 0,
 65.79,
 89.53,
 57.27,
 79.9,
 21.42,
 63.3,
 9.36,
 0,
 58.77,
 74.75,
 71.65,
 84.06,
 2.07,
 85.53,
 70.14,
 56.19,
 39.04,
 12.78,
 26.08,
 55.26,
 67.96,
 81.7,
 86.0,
 60.82,
 73.49,
 27.75,
 93.07,
 83.41,
 34.79,
 57.94,
 55.74,
 82.38,
 67.8,
 72.75,
 64.45,
 77.79,
 15.8,
 44.6,
 75.24,
 84.02,
 21.22,
 60.64,
 48.56,
 74.16,
 74.26,
 20.95,
 41.59,
 44.89,
 56.55,
 76.44,
 85.75,
 34.38,
 41.27,
 75.92,
 7.29,
 81.21,
 0.54,
 72.01,
 82.06,
 72.05,
 77.13,
 83.01,
 76.26,
 64.13,
 26.96,
 17.4,
 46.27,
 41.38,
 0,
 0,
 66.04,
 50.59,
 74.82,
 75.56,
 79.5,
 67.15,
 81.81,
 77.34,
 78.04,
 60.53,
 93.18,
 28.92,
 87.62,
 0,
 80.37,
 51.24,
 77.92,
 18.09,
 36.27,
 87.48,
 35.46,
 24.78,
 0,
 84.43,
 81.36,
 44.51,
 36.82,
 74.1,
 25.05,
 69.76,
 81.34,
 72.97,
 69.49,
 86.07,
 71.85,
 50.05,
 7.43,
 76.71,
 78.8,
 67.37,
 76.96,
 75.61,
 21.43,
 79.57,
 65.64,
 77.23,
 73.45,
 51.37,
 68.34,
 3.42,
 81.01,
 76.8,
 77.04,
 57.31,
 52.2,
 0,
 1.53,
 8.1,
 79.54,
 80.2,
 12.79,
 0,
 72.09,
 27.43,
 5.92,
 82.42,
 20.48,
 77.54,
 76.59,
 83.07,
 67.98,
 6.42,
 44.71,
 65.25,
 50.67,
 70.38,
 62.87,
 80.46,
 22.87,
 39.0,
 84.85,
 77.5,
 51.46,
 5.72,
 75.15,
 81.63,
 91.44,
 48.11,
 82.13,
 81.77,
 65.48,
 84.33,
 51.94,
 30.06,
 75.85,
 71.15,
 78.03,
 78.84,
 73.45,
 68.04,
 68.92,
 3.63,
 72.99,
 68.29,
 31.95,
 75.18,
 43.56,
 12.15,
 11.35,
 87.98,
 82.72,
 29.21,
 15.85,
 10.35,
 75.09,
 56.44,
 77.77,
 92.66,
 75.38,
 77.72,
 68.29,
 46.72,
 50.05,
 41.68,
 68.7,
 21.22,
 82.45,
 49.96,
 48.99,
 80.51]

In [11]:

# Heatmap of temperature
# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]
# Get the maximum temperature.

# Assign the figure variable.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
# Assign the heatmap variable.
heat_layer = gmaps.heatmap_layer(locations, weights=temps, dissipating=False, max_intensity=300, point_radius=4)
# Add the heatmap layer.
fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [12]:
#Adjust Heatmap Zoom, INtensity and Point Radius

In [13]:
#Now that we have created our maximum temperature heatmap, let's create the heatmap for humidity. 
#We can reuse the code and use the humidity values for the measurements.

In [14]:
# Heatmap of percent humidity
locations = city_data_df[["Lat", "Lng"]]
humidity = city_data_df["Humidity"]
fig2 = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, dissipating=False, max_intensity=300, point_radius=4)

fig2.add_layer(heat_layer)
# Call the figure to plot the data.
fig2

Figure(layout=FigureLayout(height='420px'))

In [15]:
# Heatmap of percent cloudiness.
locations = city_data_df[["Lat", "Lng"]]
clouds = city_data_df["Cloudiness"]
fig3 = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=clouds, dissipating=False, max_intensity=300, point_radius=4)

fig3.add_layer(heat_layer)
# Call the figure to plot the data.
fig3

Figure(layout=FigureLayout(height='420px'))

In [16]:
# Heatmap of percent wind speed.
locations = city_data_df[["Lat", "Lng"]]
wind = city_data_df["Wind Speed"]
fig4 = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=wind, dissipating=False, max_intensity=300, point_radius=4)

fig4.add_layer(heat_layer)
# Call the figure to plot the data.
fig4

Figure(layout=FigureLayout(height='420px'))

In [17]:
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 55
What is the maximum temperature you would like for your trip? 79

In [18]:
# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                        (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Bredasdorp,ZA,2021-12-08 20:10:22,-34.5322,20.0403,65.28,89,99,12.55
4,4,Kinablangan,PH,2021-12-08 20:10:23,7.6947,126.5503,76.66,80,100,5.95
6,6,Bengkulu,ID,2021-12-08 20:10:24,-3.8004,102.2655,74.95,91,54,4.54
9,9,Chabahar,IR,2021-12-08 20:10:26,25.2919,60.6430,72.28,59,59,2.89
10,10,Tucumcari,US,2021-12-08 20:10:26,35.1717,-103.7250,66.04,18,1,25.32
12,12,Rikitea,PF,2021-12-08 20:10:27,-23.1203,-134.9692,75.69,67,49,21.23
14,14,Inongo,CD,2021-12-08 20:10:28,-1.9500,18.2667,72.16,88,64,4.68
16,16,Ocampo,MX,2021-12-08 20:10:28,21.6500,-101.5000,72.28,15,24,9.08
19,19,Ushuaia,AR,2021-12-08 20:09:20,-54.8000,-68.3000,58.68,36,100,8.70
25,25,Esperance,AU,2021-12-08 20:10:32,-33.8667,121.9000,57.47,76,0,17.65

In [19]:
preferred_cities_df.count()

City_ID       244
City          244
Country       238
Date          244
Lat           244
Lng           244
Max Temp      244
Humidity      244
Cloudiness    244
Wind Speed    244
dtype: int64

In [20]:
preferred_cities_df.isnull().sum()

City_ID       0
City          0
Country       6
Date          0
Lat           0
Lng           0
Max Temp      0
Humidity      0
Cloudiness    0
Wind Speed    0
dtype: int64

In [21]:
preferred_cities_new_df = preferred_cities_df.dropna()
preferred_cities_new_df

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Bredasdorp,ZA,2021-12-08 20:10:22,-34.5322,20.0403,65.28,89,99,12.55
4,4,Kinablangan,PH,2021-12-08 20:10:23,7.6947,126.5503,76.66,80,100,5.95
6,6,Bengkulu,ID,2021-12-08 20:10:24,-3.8004,102.2655,74.95,91,54,4.54
9,9,Chabahar,IR,2021-12-08 20:10:26,25.2919,60.6430,72.28,59,59,2.89
10,10,Tucumcari,US,2021-12-08 20:10:26,35.1717,-103.7250,66.04,18,1,25.32
...,...,...,...,...,...,...,...,...,...,...
565,565,Caxias,PT,2021-12-08 20:25:50,38.7031,-9.2767,56.44,73,40,3.00
566,566,Inhambane,MZ,2021-12-08 20:23:34,-23.8650,35.3833,77.77,77,98,7.49
569,569,Dunmore Town,BS,2021-12-08 20:25:51,25.5000,-76.6500,77.72,79,4,5.17
570,570,Ahipara,NZ,2021-12-08 20:25:52,-35.1667,173.1667,68.29,75,100,3.62
574,574,Mathbaria,BD,2021-12-08 20:25:53,22.2876,89.9593,68.70,84,100,5.86

In [22]:
preferred_cities_new_df.count()

City_ID       238
City          238
Country       238
Date          238
Lat           238
Lng           238
Max Temp      238
Humidity      238
Cloudiness    238
Wind Speed    238
dtype: int64

In [23]:
#Using the coordinates from the preferred_cities_df DataFrame, find a hotel using our Google Places API and then retrieve that hotel information.
#Once we retrieve the hotel information, we'll need to store it so we can reference it and add the information to the pop-up marker.

In [24]:
# Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_new_df[["City", "Country", "Max Temp", "Lat", "Lng"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df

             City Country  Max Temp      Lat       Lng Hotel Name
0      Bredasdorp      ZA     65.28 -34.5322   20.0403
4     Kinablangan      PH     76.66   7.6947  126.5503
6        Bengkulu      ID     74.95  -3.8004  102.2655
9        Chabahar      IR     72.28  25.2919   60.6430
10      Tucumcari      US     66.04  35.1717 -103.7250
..            ...     ...       ...      ...       ...        ...
565        Caxias      PT     56.44  38.7031   -9.2767
566     Inhambane      MZ     77.77 -23.8650   35.3833
569  Dunmore Town      BS     77.72  25.5000  -76.6500
570       Ahipara      NZ     68.29 -35.1667  173.1667
574     Mathbaria      BD     68.70  22.2876   89.9593

[238 rows x 6 columns]

In [25]:
# Set the parameters to search for a hotel in Paris.
params = {
    "radius": 5000,
    "types": "lodging",
    "key": g_key,
    "location": "48.8566, 2.3522"}
# Use base URL to search for hotels in Paris.
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
# Make request and get the JSON data from the search.
hotels = requests.get(base_url, params=params).json()

hotels

{'html_attributions': [],
 'next_page_token': 'Aap_uEDC2bVZMObl5VKXiSWUU1MkKy84uUi6bugDycpiQ_reVivP5FUWzOgvyU14Qj5yul8RWxG18AVoViyU_TYDp3ExVMo8sz_gPOPc8RFsBZirSf9DsV76WUGVW5WS8b3WQeJUhueN74B2Bfz73dBrwXW4DkrpWe_4rHWj1RD3HIDXHGCooGFeNOOq8fakxQ4lbNmPsoh2023ly2bCqr-3pyz7sjZsdOTiLGxpjgcX6HuOo0RWCfpZcBR2S6FCo3r3Ytqg_J5Rc-ly6iwaiTwMTP-jToh33GCf9PXUQ6l52eZ0DZWv85amfzZfILKSU13wvmQElrkPq7M5YcG4tAFUCm1sFfkkFg3UUTCSVM0-sFKkDE0YVBDvlgGnD3bOqBWSkK8jxYaXKpG5oKJRPVZdfM-OhksbVqDPvIfQi0hzKQBf2o3cMbVz4N1f',
 'results': [{'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8581126, 'lng': 2.3529277},
    'viewport': {'northeast': {'lat': 48.8594360302915,
      'lng': 2.354355480291502},
     'southwest': {'lat': 48.8567380697085, 'lng': 2.351657519708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Hôtel Duo',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 3840,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/107554201425443337224">Hôtel Duo</a>'],
     'photo_reference': 'Aap_uEBxP9coin2bgXrvShzT15uP9SGioOtQ1ypEhw3wUIUXU69JTOnCpt6jocvZcg5OJN_Y8OtsKkIR4n2Inh8IXpGa6MZQ7T1TcgiFX0ssvhFm9Sjj7U_zJC9h6VAfnIciEChz2k79OhqfP_ij8Z0-_SxTiIL2i93IJCDSw73Ia6txKAe8',
     'width': 5760}],
   'place_id': 'ChIJWU9CqB1u5kcR5P1F2SMoJmc',
   'plus_code': {'compound_code': 'V953+65 Paris, France',
    'global_code': '8FW4V953+65'},
   'rating': 4.2,
   'reference': 'ChIJWU9CqB1u5kcR5P1F2SMoJmc',
   'scope': 'GOOGLE',
   'types': ['night_club',
    'spa',
    'lodging',
    'bar',
    'gym',
    'health',
    'point_of_interest',
    'establishment'],
   'user_ratings_total': 311,
   'vicinity': '11 Rue du Temple, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8582861, 'lng': 2.3464944},
    'viewport': {'northeast': {'lat': 48.85954748029151,
      'lng': 2.347782830291502},
     'southwest': {'lat': 48.85684951970851, 'lng': 2.345084869708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Hôtel Britannique - Paris Centre',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 1426,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/108984000175492464929">Hôtel Britannique - Paris Centre</a>'],
     'photo_reference': 'Aap_uEARhCdIwP9WKeF7FnFRk4fzrgL5e84-IHepoitANk_NaUMMkwTr7oXx7_XONlyeLlizWBLYeYZ4TLMXagQv6K9aViRVqgPyeHJo_ymUsNFHMjvttoZ3ir-Xihwrt1KwCJmlpCTiHHSL4_YTIZwxrw-SUq-GVbSpmxbSS1j-9mcUB8zN',
     'width': 1476}],
   'place_id': 'ChIJ-4Siox9u5kcRm9vM6DcMXyU',
   'plus_code': {'compound_code': 'V85W+8H Paris, France',
    'global_code': '8FW4V85W+8H'},
   'rating': 4.6,
   'reference': 'ChIJ-4Siox9u5kcRm9vM6DcMXyU',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 650,
   'vicinity': '20 Avenue Victoria, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8606655, 'lng': 2.3469293},
    'viewport': {'northeast': {'lat': 48.8617653302915,
      'lng': 2.348020880291502},
     'southwest': {'lat': 48.85906736970851, 'lng': 2.345322919708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Citadines Les Halles Paris',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 853,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/102565262508115704337">Citadines Les Halles Paris (Apart hotel Paris)</a>'],
     'photo_reference': 'Aap_uEC1eL6OxFEWF5MTEpzRIvD9rLCRvfpSBsI_TsulZaDpocUNevk7wFedz4Ljv5I9kXjQh6avtkTKAMhfZn9-mgmWl5uZz6Xgkawij72d1awXDP5VRcWmDVTUoywERiQJAfJG15r2Xe9uMejw0jnL7UcwD6qKey_v097t2swwRc9rnwjI',
     'width': 1280}],
   'place_id': 'ChIJQ_QDrxhu5kcRJzNxLLEOSfU',
   'plus_code': {'compound_code': 'V86W+7Q Paris, France',
    'global_code': '8FW4V86W+7Q'},
   'rating': 4.1,
   'reference': 'ChIJQ_QDrxhu5kcRJzNxLLEOSfU',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 874,
   'vicinity': '4 Rue des Innocents, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8607658, 'lng': 2.3465318},
    'viewport': {'northeast': {'lat': 48.8620584302915,
      'lng': 2.347692880291501},
     'southwest': {'lat': 48.85936046970851, 'lng': 2.344994919708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Novotel Paris Les Halles',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 2000,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/111815616573299411056">Novotel Paris Les Halles</a>'],
     'photo_reference': 'Aap_uEDDZHq7ys7cjBWN35w8QB_O-s_aK_nNwpQl3hPxGeFJOnSHbo2uUlr0MOeQgCjB504uWNG5h8SLO3J-GETLZ7cANkqqCaenEcPXOeFxsWyuOg7iM04otBDOkgZnqS7gEYTO51wOx6VZYhnekrDjgMAW51WssObGihADVQMJU_sdUN2I',
     'width': 3000}],
   'place_id': 'ChIJGW2pNx9u5kcRI3oyL8NG5BQ',
   'plus_code': {'compound_code': 'V86W+8J Paris, France',
    'global_code': '8FW4V86W+8J'},
   'rating': 4.4,
   'reference': 'ChIJGW2pNx9u5kcRI3oyL8NG5BQ',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 2308,
   'vicinity': '8 Place Marguerite de Navarre, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.860352, 'lng': 2.3440948},
    'viewport': {'northeast': {'lat': 48.86165553029149,
      'lng': 2.345549080291502},
     'southwest': {'lat': 48.8589575697085, 'lng': 2.342851119708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Hôtel Ducs de Bourgogne',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 1390,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/101411638353598558320">Hôtel Ducs de Bourgogne</a>'],
     'photo_reference': 'Aap_uEDL5T21sZvA5BnMkjcbutZOZFobo0ek0meG88VijyjuhdzOS819eD3bi4asMHdrsAHl_wd2A376PybS_fZgdSlbfvnmtl5HaqDreTKgCJq1R-hR-GxrU3wYyt-1k3hQhBjzGJkq01MnOx-ZGO2PwOKY7zzOUaUc7GMrb1R5_S6K83kP',
     'width': 2048}],
   'place_id': 'ChIJifTG5yFu5kcRdnisbwxnAx4',
   'plus_code': {'compound_code': 'V86V+4J Paris, France',
    'global_code': '8FW4V86V+4J'},
   'rating': 4.5,
   'reference': 'ChIJifTG5yFu5kcRdnisbwxnAx4',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 280,
   'vicinity': '19 Rue du Pont Neuf, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8555091, 'lng': 2.3408736},
    'viewport': {'northeast': {'lat': 48.8569076302915,
      'lng': 2.342319280291502},
     'southwest': {'lat': 48.8542096697085, 'lng': 2.339621319708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Citadines Saint-Germain-des-Prés Paris (Apart hotel Paris)',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 4480,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/113188832595116816387">Citadines Saint-Germain-des-Prés Paris</a>'],
     'photo_reference': 'Aap_uEDLTkyOtSQrtdZOM_3Ex29sP9r_63gcD39k8iL5B1BTcoWVkdPwuaeYqKS5ueOprrk-e1gYFD07GkwvMRquqjiGIGUGdb7u-sS2W3VxV-lmEe0I1VeDU_G9t-441rxT35yPEeqY9L8E7TAbDzmNN8QLCygxItedHMxVYv65mHaqfvT7',
     'width': 6720}],
   'place_id': 'ChIJo5pYcN9x5kcRERXdocMgqmE',
   'plus_code': {'compound_code': 'V84R+68 Paris, France',
    'global_code': '8FW4V84R+68'},
   'rating': 4.3,
   'reference': 'ChIJo5pYcN9x5kcRERXdocMgqmE',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 717,
   'vicinity': '53 ter Quai des Grands Augustins, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8663519, 'lng': 2.3606461},
    'viewport': {'northeast': {'lat': 48.86775308029149,
      'lng': 2.361905130291502},
     'southwest': {'lat': 48.8650551197085, 'lng': 2.359207169708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Paris France Hôtel',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 2673,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/102332962500946068613">Paris France Hôtel</a>'],
     'photo_reference': 'Aap_uEDbHGLYdorigS-JdKbB5HttTdMuXZWvF3Ct6vM7NbpQnnkrPgj5ynQdfiQ9dLObKCUjs07n_h3M4ToaoaVtItpV8kyai-P4F131Omd1FQ_dz6smomQsMPKbKHguJKzumajS4QGEcmBGaJ7Qw3pmsfeEmYAk_KObxEgbLwGyeEyPMspf',
     'width': 3463}],
   'place_id': 'ChIJhXWLZg9u5kcRDVyqoZYgcmg',
   'plus_code': {'compound_code': 'V986+G7 Paris, France',
    'global_code': '8FW4V986+G7'},
   'rating': 4.3,
   'reference': 'ChIJhXWLZg9u5kcRDVyqoZYgcmg',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 397,
   'vicinity': '72 Rue de Turbigo, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.86386539999999, 'lng': 2.3325488},
    'viewport': {'northeast': {'lat': 48.8650759802915,
      'lng': 2.333775730291502},
     'southwest': {'lat': 48.8623780197085, 'lng': 2.331077769708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Hotel Regina Louvre',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 3700,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/109908333790946649027">Hôtel Regina Louvre</a>'],
     'photo_reference': 'Aap_uEDwkuYvoQR7s01QUolE-fDJwy0ORlQuSZQaGJPQ9qOK3bdT6jiDx2Vx_G15CpkOG5h-eNDhngRn-e7tTRMrtytaoKJJgCFzs-4QCWI-PAjOZ1_gT66OLty10wvXScLjCj7xlyVBu2QeAl0EreX93uF1m4ypqUbD6of0ucbI1ydHyTsx',
     'width': 5550}],
   'place_id': 'ChIJP_-HCS9u5kcRsj9b1x7Pl8w',
   'plus_code': {'compound_code': 'V87M+G2 Paris, France',
    'global_code': '8FW4V87M+G2'},
   'rating': 4.4,
   'reference': 'ChIJP_-HCS9u5kcRsj9b1x7Pl8w',
   'scope': 'GOOGLE',
   'types': ['lodging',
    'bar',
    'restaurant',
    'food',
    'point_of_interest',
    'establishment'],
   'user_ratings_total': 508,
   'vicinity': '2 Place des Pyramides, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.84795229999999, 'lng': 2.370869},
    'viewport': {'northeast': {'lat': 48.8492035302915,
      'lng': 2.372290080291501},
     'southwest': {'lat': 48.8465055697085, 'lng': 2.369592119708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'ibis Paris Gare de Lyon Ledru Rollin 12ème',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 2048,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/101181280085797863615">Kevin Nguyen</a>'],
     'photo_reference': 'Aap_uEB9JrXjyDT_TYneQqC3bm1eoCyyZw2J39WTVJKNrcm7R9lyYUCJVzV0H18FHYmlwbSyjl4N8qWN4GwXmR8ZRkvwpm2BLQmEj_c_MRkEycjqhf311iRsTwHFgLuOQOV2sKiV6_clPKRlXNwsnB3C5w11fT6wXYQ_kIfjM7UDXUdV-Qx5',
     'width': 1536}],
   'place_id': 'ChIJ9RNxcQNy5kcRnZJ4vsuXcow',
   'plus_code': {'compound_code': 'R9XC+58 Paris, France',
    'global_code': '8FW4R9XC+58'},
   'rating': 4.1,
   'reference': 'ChIJ9RNxcQNy5kcRnZJ4vsuXcow',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 844,
   'vicinity': '41/43 Avenue Ledru Rollin, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8710647, 'lng': 2.34991},
    'viewport': {'northeast': {'lat': 48.87241888029151,
      'lng': 2.351188530291502},
     'southwest': {'lat': 48.86972091970851, 'lng': 2.348490569708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Hôtel des Comédies Paris',
   'photos': [{'height': 4000,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/114696623290303183213">Noble</a>'],
     'photo_reference': 'Aap_uEC4MU8-rB-bqrVNBnKS6KKsYSvWcqlvX8UIe3iio5mHqTCVzqM9_ZB1W6-e796FJjcxTn7gALiLKSSrhn0tduTAYpe3e2_7M1k5YbGQdwBgG_oA8SSAvjzwtMAEDyr00nOePWmkt6VRiDmknAARM5ErMtYC68qDGYJjpzwQD6aPhI96',
     'width': 3000}],
   'place_id': 'ChIJn6ginxZu5kcRmAEK0OHm0cI',
   'plus_code': {'compound_code': 'V8CX+CX Paris, France',
    'global_code': '8FW4V8CX+CX'},
   'rating': 4.2,
   'reference': 'ChIJn6ginxZu5kcRmAEK0OHm0cI',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 199,
   'vicinity': "8 Rue d'Hauteville, Paris"},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.84754640000001, 'lng': 2.3718722},
    'viewport': {'northeast': {'lat': 48.8488820802915,
      'lng': 2.373123430291502},
     'southwest': {'lat': 48.8461841197085, 'lng': 2.370425469708499}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Hôtel De France Gare de Lyon Bastille',
   'photos': [{'height': 787,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/117462031751048846575">Hôtel De France Gare de Lyon Bastille</a>'],
     'photo_reference': 'Aap_uEB1DFdJIPN9Rhq9Aau12vUtob-YlkJWk23NkyHPFlV63k2AVo3aRa1GsssB28BCFXQbl7hkFGq94FpvVGndP6WwKsE9RG4m_zSJqmDii8hRW-Kg9hefSvUQDKpTqNLNJ5i14zfZ4RxdkL38mgwLhvd45o7cJLlNt9jrt9L_r5ymrvL3',
     'width': 1181}],
   'place_id': 'ChIJz6DBYgNy5kcRhOu1LhDIECM',
   'plus_code': {'compound_code': 'R9XC+2P Paris, France',
    'global_code': '8FW4R9XC+2P'},
   'rating': 3.3,
   'reference': 'ChIJz6DBYgNy5kcRhOu1LhDIECM',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 382,
   'vicinity': '12 Rue de Lyon, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8717386, 'lng': 2.3447052},
    'viewport': {'northeast': {'lat': 48.8731374802915,
      'lng': 2.346059980291502},
     'southwest': {'lat': 48.8704395197085, 'lng': 2.343362019708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Hôtel Prélude Opéra Paris',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 2448,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/106224131803115407650">Marcin Marczak</a>'],
     'photo_reference': 'Aap_uEC8BFt6gVfIG0pm9sMDmwwiChDTP2FahkF_rF2SE5g_MUptJbgIfjgfYSSbSXZ5tIAEtHuEjvGhN8liB8PsDGvDYX6oSe5RzFAfPP_NppHy9QSLYDROcJqDf4qd9jK5nl6oJYS6QnxBWJQywN2jRMOFK7QDGAIRK80f9er29RHVwJ4I',
     'width': 3264}],
   'place_id': 'ChIJ8e3Qcj5u5kcR2MIGwNxustk',
   'plus_code': {'compound_code': 'V8CV+MV Paris, France',
    'global_code': '8FW4V8CV+MV'},
   'rating': 4.2,
   'reference': 'ChIJ8e3Qcj5u5kcR2MIGwNxustk',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 393,
   'vicinity': '8 Cité Bergère, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8423434, 'lng': 2.3632087},
    'viewport': {'northeast': {'lat': 48.8436624802915,
      'lng': 2.364700930291502},
     'southwest': {'lat': 48.8409645197085, 'lng': 2.362002969708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Hôtel Libertel Austerlitz Jardin des Plantes',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 4480,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/114802271282641766772">Hôtel Libertel Austerlitz Jardin des Plantes</a>'],
     'photo_reference': 'Aap_uEA-18_6hF29hLdMQUetMLclocb3J5e1NjkPw8m2DfCJvpEK3fBNkNrK4fLmw-D-KYlb8HPnVd2QsgFXbmhZWXKjBPaAoEP6UEObtg1GIFCkJq_mOaguTjjb15vCTIrxWbFWy4rHcoFHK0elOc23gE5glh7B0YyU5klYlchZVmHvg5-9',
     'width': 6720}],
   'place_id': 'ChIJe-udXPZx5kcRKURHNFv5BSw',
   'plus_code': {'compound_code': 'R9R7+W7 Paris, France',
    'global_code': '8FW4R9R7+W7'},
   'rating': 3.9,
   'reference': 'ChIJe-udXPZx5kcRKURHNFv5BSw',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 453,
   'vicinity': "12 Boulevard de l'Hôpital, Paris"},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8642974, 'lng': 2.3308142},
    'viewport': {'northeast': {'lat': 48.8655789302915,
      'lng': 2.332153980291502},
     'southwest': {'lat': 48.8628809697085, 'lng': 2.329456019708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Saint James Albany Paris Hôtel Spa',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 400,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/108570400659068256718">Saint James Albany Paris Hôtel Spa</a>'],
     'photo_reference': 'Aap_uEDjUEfhPfs7Gxd-4GPlcJXlun0BkVw2Kpe0bdgNXIf08nMhELMn05ixwvwxJE8cdmz4imIoPh64zjBY64khYDImlHEHFlNGYrhx3nL1eLrqe0W_W5cc_RpeUkhsj3s6_eZdqepVoMI9zCKF-MYNT4ZN3gXOafAANKz6Yvk0_sABamft',
     'width': 600}],
   'place_id': 'ChIJ8znTVS5u5kcREq8TmzOICFs',
   'plus_code': {'compound_code': 'V87J+P8 Paris, France',
    'global_code': '8FW4V87J+P8'},
   'rating': 4,
   'reference': 'ChIJ8znTVS5u5kcREq8TmzOICFs',
   'scope': 'GOOGLE',
   'types': ['lodging',
    'bar',
    'restaurant',
    'food',
    'point_of_interest',
    'establishment'],
   'user_ratings_total': 1075,
   'vicinity': '202 Rue de Rivoli, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.87110329999999, 'lng': 2.3389728},
    'viewport': {'northeast': {'lat': 48.8724169302915,
      'lng': 2.340369280291502},
     'southwest': {'lat': 48.8697189697085, 'lng': 2.337671319708499}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Hôtel Icône',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 1066,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/108137830440312077288">Hôtel Icône</a>'],

In [26]:
#number of hotels near specified location.
len(hotels["results"])

20

In [27]:
#Now that we know how to retrieve the hotel name from the JSON data, we can iterate over the rows in the hotel_df DataFrame for the coordinates.

In [28]:
#We can use the iterrows() function to perform the iteration; however, we need to provide the index and the row in the for loop using this syntax: for index, row in df.iterrows()

In [29]:
# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
    # Grab the first hotel from the results and store the name.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")  

hotel_df.head(10)

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

,City,Country,Max Temp,Lat,Lng,Hotel Name
0,Bredasdorp,ZA,65.28,-34.5322,20.0403,Bredasdorp Country Manor
4,Kinablangan,PH,76.66,7.6947,126.5503,Morales Eatery and Lodging House
6,Bengkulu,ID,74.95,-3.8004,102.2655,Grage Hotel Bengkulu
9,Chabahar,IR,72.28,25.2919,60.6430,هتل گدروشیا
10,Tucumcari,US,66.04,35.1717,-103.7250,"Holiday Inn Express & Suites Tucumcari, an IHG..."
12,Rikitea,PF,75.69,-23.1203,-134.9692,People ThankYou
14,Inongo,CD,72.16,-1.9500,18.2667,Hotel Du Lac
16,Ocampo,MX,72.28,21.6500,-101.5000,Hotel Estancia del Vaquero
19,Ushuaia,AR,58.68,-54.8000,-68.3000,Albatros Hotel
25,Esperance,AU,57.47,-33.8667,121.9000,Hospitality Esperance

In [35]:
hotel_df.count()

City          238
Country       238
Max Temp      238
Lat           238
Lng           238
Hotel Name    238
dtype: int64

In [30]:
#Create a Maximum Temperature Heatmap from a Hotel DataFrame

In [36]:
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

In [37]:
# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

In [38]:
#Add a heatmap of temperature for the vacation spots.
locations = hotel_df[["Lat", "Lng"]]
max_temp_1 = hotel_df['Max Temp']
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp_1, dissipating=False,
                                max_intensity=300, point_radius=4)
#Let's add the markers for each city on top of the heatmap. 
#Edit the code we used to create the heatmap to look like the following:
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
#Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))